baseURL = "https://bellonet.github.io/image-registration-workshop/"
languageCode = "en-us"
title = "Image Registration Workshop"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
